const useFetchProperties = () => {
  const properties = [
    {
      id: 1,
      title: "4 Bedroom Townhouse",
      location: "Karen, Nairobi",
      price: 85000000,
      image: "/properties/property-1.jpg",
      bedrooms: 4,
      bathrooms: 4,
      parking: true,
      gym: false,
      lift: false,
      pool: true,
    },
    {
      id: 2,
      title: "3 Bedroom Apartment",
      location: "Kilimani, Nairobi",
      price: 32000000,
      image: "/properties/property-2.jpg",
      bedrooms: 3,
      bathrooms: 3,
      parking: true,
      gym: true,
      lift: true,
      pool: false,
    },
    {
      id: 3,
      title: "5 Bedroom Standalone House",
      location: "Runda, Nairobi",
      price: 120000000,
      image: "/properties/property-3.jpg",
      bedrooms: 5,
      bathrooms: 5,
      parking: true,
      gym: false,
      lift: false,
      pool: true,
    },
    {
      id: 4,
      title: "2 Bedroom Apartment",
      location: "Westlands, Nairobi",
      price: 21000000,
      image: "/properties/property-4.jpg",
      bedrooms: 2,
      bathrooms: 2,
      parking: true,
      gym: true,
      lift: true,
      pool: false,
    },
    {
      id: 5,
      title: "4 Bedroom Villa",
      location: "Lavington, Nairobi",
      price: 95000000,
      image: "/properties/property-5.jpg",
      bedrooms: 4,
      bathrooms: 4,
      parking: true,
      gym: true,
      lift: false,
      pool: true,
    },
    {
      id: 6,
      title: "3 Bedroom Apartment",
      location: "Kileleshwa, Nairobi",
      price: 28000000,
      image: "/properties/property-6.jpg",
      bedrooms: 3,
      bathrooms: 3,
      parking: true,
      gym: false,
      lift: true,
      pool: false,
    },
  ];

  return { properties };
};

export default useFetchProperties;
